<?php

namespace AppBundle\Repository;

/**
 * LoginDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoginDateRepository extends \Doctrine\ORM\EntityRepository
{
}
